name: MLflow CI - Retrain & Build Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  CSV_URL: "MLProject/telco_preprocessing"

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install MLflow & dependencies
        run: |
          pip install mlflow==2.19.0 pandas scikit-learn joblib

      - name: Run MLflow Project (retrain model)
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local

      - name: Get latest MLflow run id
        working-directory: MLProject
        run: |
          RUN_ID=$(python -c "import mlflow; from mlflow.tracking import MlflowClient; c=MlflowClient(); exp=c.get_experiment_by_name('Default'); runs=c.search_runs(exp.experiment_id, order_by=['start_time DESC'], max_results=1); print(runs[0].info.run_id)")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run id: $RUN_ID"

      - name: Upload MLflow artifacts to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-artifacts
          path: MLProject/mlruns

      - name: Build Docker image from MLflow model
        working-directory: MLProject
        run: |
          echo "Building docker image for RUN_ID=${RUN_ID}"
          mlflow models build-docker \
            --model-uri "runs:/${RUN_ID}/model" \
            --name "telco-churn-model" \
            --env-manager conda

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag & push image to Docker Hub
        run: |
          docker tag telco-churn-model ${{ secrets.DOCKERHUB_USERNAME }}/telco-churn-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-churn-model:latest
